---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    region: eu-north-1
    keyname: lab1_ec
    allowed_ip: 195.200.245.21/32
    instance_type: t3.micro
    image: ami-08bdc08970fcbd34a
  tasks:
    - name: create key pair
      tags: keypair
      ec2_key:
        region: "{{ region }}"
        name: "{{ keyname}}"
      register: mykey

    - name: write the private key to file
      copy: content="{{ mykey.key.private_key }}" dest="~/.ssh/{{ keyname }}.pub" mode=0600
      when: mykey.changed
    
    - name: create security group
      tags: sg
      ec2_group:
        region: "{{ region }}"
        #your security group name
        name: SG_Lab1 
        description: security group for apsydney webserver host
        rules:
          # allow ssh access from your ip address
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ allowed_ip }}"
            # allow http access from anywhere
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            # allow https access from anywhere
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    
    - name: launch ec2 instance
      tags: ec2_instance 
      ec2:
        region: "{{ region }}"
        key_name: "{{ keyname }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: SG_Lab1
        id: wordpress_launch_1
        instance_tags:
          Name: wordpress-1
          class: wordpress
      register: ec2_instance

    - name: associate new EIP for the instance
      tags: eip
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
      when: item.id is defined
    
